### ISSUE TITLE
IOS8 or later have some bug

### ISSUE THREAD

**Issue by scp173** [dbsGen/SlimeRefresh#10]
i found some bug when my tableview add tableheaderview and pull it ,the animate was strange

**Comment by dbsGen** [comment]
Fixed commit dc94e3282f.
And I update the demo, maybe it is useful. Errr I think it would work.

**Comment by scp173** [comment]
same problem,i avoid this bug
 - (void)scrollViewDidEndDraging
{
    if (_broken) {
        if (self.loading) {
            [UIView transitionWithView:_scrollView.superview
                              duration:0.2
                               options:0
                            animations:^{
                                UIEdgeInsets inset = _scrollView.contentInset;
                                inset.top = -_scrollView.contentOffset.y;
                                _scrollView.contentInset = inset;
                            } completion:^(BOOL finished) {
                                self.broken = NO;

                                [UIView transitionWithView:_scrollView.superview
                                                  duration:0.2
                                                   options:0
                                                animations:^{
                                                    UIEdgeInsets inset = _scrollView.contentInset;
                                                    inset.top = _upInset + _dragingHeight;
                                                    _scrollView.contentInset = inset;
                                                } completion:^(BOOL finished) {
                                                    self.broken = NO;


                                                    
                                                }];


                            }];
            [UIView beginAnimations:nil context:NULL];
            [UIView setAnimationDuration:0.2f];
            [UIView commitAnimations];
        }else {
            [self performSelector:@selector(setBroken:)
                       withObject:nil afterDelay:0.2];
            self.loading = NO;
        }
    }
}
this is useful,thank u guys,your code is awesome ^_^
