### ISSUE TITLE
leaving gap without UINavigationBar

### ISSUE THREAD

**Issue by tobatha** [dbsGen/SlimeRefresh#11]
this is very weird, in the demo, i manually hide the nav bar, and when i pull down i will have to pull far enough to get the slime visible, seems like the same height as nav bar

and when the activity animation finished, the table will not get back to where table originally  would be
[_slimeView update:64];
it'll go back to above value setup to update when slimeview init.

i have to giveup the component, but awesome animation anyway, if only it'll also work without Nav bar

**Comment by dbsGen** [comment]
It is easy! try this. 

        [_slimeView update:20];
        _slimeView.slime.viscous = 44;

**Comment by tobatha** [comment]
cool ! it works.......
may i ask why, coz i tried to fix it by my own, but seems no luck, i noticed this viscous might cause the problem but can't figure it out!

**Comment by dbsGen** [comment]
The bigger viscous, The farther the pull broken the slime.
I push a new commit 38784542c683854e484f8f58414385046a64f4c9.
viscous no longer set to smaller than 32 when use -update:upIset.

**Comment by tobatha** [comment]
okiedokie, got cha!
sweet, thank you very much! Really appreciate it.
