### ISSUE TITLE
可能导致 TableView 或者 ScrollView 无法释放的问题

### ISSUE THREAD

**Issue by CocodyChou** [dbsGen/SlimeRefresh#12]
我注意到`SRRefreshView.m`文件中
`@property (nonatomic, strong)   UIScrollView    *scrollView;`
这会和 ScrollView 形成循环强引用，导致无法释放，频繁操作将导致内存泄漏。
如果 Cell 内使用了观察者，将导致观察者引起的 Crash。

**Comment by dbsGen** [comment]
在controller中加入这段
      - (void)dealloc {
         ....
         [refreshView removeFromSuperview]; 
      }
