### ISSUE TITLE
一个可能导致 Crash 的问题

### ISSUE THREAD

**Issue by CocodyChou** [dbsGen/SlimeRefresh#13]
我注意到在`SRRefreshView.h`文件中
`@property (nonatomic, assign)   id<SRRefreshDelegate>   delegate;`
使用了 assign 修饰 object。如果 delegate 指向的对象释放，assign并不能自动置为nil，此时再向 delegate 发送消息，则会 crash。俗称野指针。

**Comment by dbsGen** [comment]
实际上几乎所有的delegate都是assign的，这个指针应该由你自己来管理，在delegate对象释放的时候把它置为空。这点你可以查看官方api，不确定是否有新的修饰能够自动设置为空。

**Comment by CocodyChou** [comment]
如果使用 weak，则可在对象释放后自动置为 nil

**Comment by dbsGen** [comment]
谢谢你，不过组件能运行在iOS4.0上也是它的一个特色，暂时并没有修改的意思。很多官方api也还是用的assign,自己管理这个指针应该不是一个大问题。

**Comment by CocodyChou** [comment]
OK，不过有个疑问，scrollView可以用strong，为什么用了weak就不能支持 iOS4.0了呢？

发自我的 iPhone

**Comment by CocodyChou** [comment]
另外，还是非常感谢你提供的代码，效果非常赞！调整也方便！

发自我的 iPhone

**Comment by dbsGen** [comment]
据我所知strong在arc出现的时候就能用了,weak是之后添加的,抱歉之前没看.

**Comment by CocodyChou** [comment]
没关系！

strong 和 weak 不是成对出现的啊？孤陋寡闻了

发自我的 iPhone
