### ISSUE TITLE
貌似不支持webview

### ISSUE THREAD

**Issue by tobatha** [dbsGen/SlimeRefresh#16]
按README放到UIWebview, 貌似不行

**Comment by dbsGen** [comment]
- (void)viewDidLoad
    {
        [super viewDidLoad];
    
        CGRect bounds = self.view.bounds;
        _webView = [[UIWebView alloc] initWithFrame:CGRectMake(0, 0, bounds.size.width, bounds.size.height)];
        bounds.size.height += 1;
        [self.view addSubview:_webView];
        [_webView loadRequest:[NSURLRequest requestWithURL:[NSURL URLWithString:@"https://www.baidu.com"]]];
    
        _slimeView = [[SRRefreshView alloc] init];
        _slimeView.delegate = self;
        _slimeView.slimeMissWhenGoingBack = YES;
        _slimeView.slime.bodyColor = [UIColor blackColor];
        _slimeView.slime.skinColor = [UIColor whiteColor];
        _slimeView.slime.lineWith = 1;
        _slimeView.slime.shadowBlur = 4;
        _slimeView.slime.shadowColor = [UIColor blackColor];
    
        _webView.autoresizingMask = UIViewAutoresizingFlexibleWidth| UIViewAutoresizingFlexibleHeight;
        _webView.scrollView.delegate = self;
        [_webView.scrollView addSubview:_slimeView];
    
        [_slimeView update:64];
    }

这样就可以了

**Comment by tobatha** [comment]
噢, 好的, 多谢! 我试试看~
